//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_crud_first_Approach.context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        public int id { get; set; }
        [Required (ErrorMessage ="Required")]
        public string name { get; set; }
        [Required (ErrorMessage = "Required")]
        public Nullable<int> rollno { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> age { get; set; }
            [Required(ErrorMessage = "Required")]
      public string city { get; set; }
    }
}
